version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=pass

  postgres:
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    # volumes:
    #   - ./db_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
